# Schema for the configuration files of the Drupalfr releases module.

drupalfr_releases.settings:
  type: config_object
  label: 'Settings for Releases'
  mapping:
    xml_address:
      type: string
      label: 'XML address'
