# Schema for the configuration files of the Drupalfr meetup module.

drupalfr_meetup.settings:
  type: config_object
  label: 'Settings for Meetup connection'
  mapping:
    api_key:
      type: string
      label: 'API key'
    group_url_name:
      type: string
      label: 'Group URL name'
